apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: static-web-deployment
        image: prili/static_web:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
